EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'Shoe2Shop'
GO
USE [master]
GO

IF (EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE ('[' + name + ']' = N'Shoe2Shop' OR name = N'Shoe2Shop')))
DROP DATABASE [Shoe2Shop]
GO

CREATE DATABASE [Shoe2Shop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Shoe2Shop', FILENAME = N'D:\BD\DATA\Shoe2Shop.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Shoe2Shop_log', FILENAME = N'D:\BD\DATA\Shoe2Shop_log.ldf' , SIZE = 2048KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Shoe2Shop] SET COMPATIBILITY_LEVEL = 110
GO
ALTER DATABASE [Shoe2Shop] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Shoe2Shop] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Shoe2Shop] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Shoe2Shop] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Shoe2Shop] SET ARITHABORT OFF 
GO
ALTER DATABASE [Shoe2Shop] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Shoe2Shop] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Shoe2Shop] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Shoe2Shop] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Shoe2Shop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Shoe2Shop] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Shoe2Shop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Shoe2Shop] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Shoe2Shop] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Shoe2Shop] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Shoe2Shop] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Shoe2Shop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Shoe2Shop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Shoe2Shop] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Shoe2Shop] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Shoe2Shop] SET  READ_WRITE 
GO
ALTER DATABASE [Shoe2Shop] SET RECOVERY FULL 
GO
ALTER DATABASE [Shoe2Shop] SET  MULTI_USER 
GO
ALTER DATABASE [Shoe2Shop] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Shoe2Shop] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

USE [Shoe2Shop]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Shoe2Shop] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO